# Generated by Django 4.2.7 on 2025-06-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('search_query', models.CharField(max_length=200, verbose_name='搜索关键词')),
                ('source', models.CharField(max_length=50, verbose_name='数据源')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='结果数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '刮削日志',
                'verbose_name_plural': '刮削日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='剧集名称')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='原始标题')),
                ('overview', models.TextField(blank=True, verbose_name='剧情简介')),
                ('poster_url', models.URLField(blank=True, verbose_name='海报URL')),
                ('backdrop_url', models.URLField(blank=True, verbose_name='背景图URL')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='本地海报')),
                ('backdrop_image', models.ImageField(blank=True, null=True, upload_to='backdrops/', verbose_name='本地背景图')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, verbose_name='TMDB ID')),
                ('imdb_id', models.CharField(blank=True, max_length=20, verbose_name='IMDB ID')),
                ('douban_id', models.CharField(blank=True, max_length=20, verbose_name='豆瓣ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='年份')),
                ('genres', models.CharField(blank=True, max_length=200, verbose_name='类型')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='状态')),
                ('total_episodes', models.PositiveIntegerField(blank=True, null=True, verbose_name='总集数')),
                ('tmdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='TMDB评分')),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='IMDB评分')),
                ('douban_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='豆瓣评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '剧集',
                'verbose_name_plural': '剧集',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['series', 'season_number', 'episode_number', '-created_at'], 'verbose_name': '影片', 'verbose_name_plural': '影片'},
        ),
        migrations.AddField(
            model_name='movie',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='集数'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='IMDB ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='原始标题'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='episode_posters/', verbose_name='剧集海报'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, verbose_name='海报URL'),
        ),
        migrations.AddField(
            model_name='movie',
            name='season_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='季数'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='TMDB ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.series', verbose_name='所属剧集'),
        ),
    ]
